# Use Golang official base image
FROM golang:1.24-alpine

# Set environment
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod tidy

# Copy the whole project
COPY . .

# Build Go app
RUN go build -o user-service

# Expose port
EXPOSE 8080

# Run the binary
CMD ["./user-service"]
